config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:create, :destroy, :new]
  resources :goals do
    member do
      post 'toggle'
      post 'cheer'
    end
  end
  resources :comments, only: [:create, :destroy]
end

app/models/cheer.rb
class Cheer < ActiveRecord::Base
  belongs_to :user
  belongs_to :goal
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author_id, :commentable_id, :commentable_type, :body, presence: true

  belongs_to :commentable, polymorphic: true
  belongs_to :author, class_name: "User"
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable, dependent: :destroy
  end

  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  include Commentable

  validates :body, :user_id, presence: true

  after_initialize :set_default_completed

  belongs_to :user

  has_many :cheers
  has_many :cheerers, through: :cheers

  def set_default_completed
    self.completed ||= false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Commentable

  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  has_many :cheerings, class_name: "Cheer"
  has_many :cheered_goals, through: :cheerings, source: :goal
  has_many :goals
  has_many :authored_comments, class_name: "Comment", foreign_key: :author_id

  after_initialize :ensure_session_token, :set_num_cheers

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    user && user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    save!
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def set_num_cheers
    self.cheers ||= 5
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_logged_in
    return if current_user
    redirect_to new_session_url
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.authored_comments.new(comment_params)

    if @comment.save
      flash[:success] = "Comment created!"
      if @comment.commentable_type == "User"
        redirect_to user_url(@comment.commentable_id)
      else
        redirect_to user_url(@comment.commentable.user_id)
      end
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    if @comment.commentable_type == "User"
      redirect_to user_url(@comment.commentable_id)
    else
      redirect_to user_url(@comment.commentable.user_id)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body, :commentable_id, :commentable_type)
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_logged_in
  before_action :require_correct_user, except: [:new, :create]

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)

    if @goal.save
      flash[:success] = "Goal created!"
      redirect_to current_user
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update(goal_params)
      redirect_to current_user
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def cheer
    @goal = Goal.find(params[:id])
    @user = current_user
    if @user.cheers > 0
      Cheer.create(user_id: current_user.id, goal_id: @goal.id)
      @user.cheers -= 1
      @user.save
      redirect_to :back
    else
      flash[:errors] = "No cheers left!"
      redirect_to :back
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to current_user
  end

  def toggle
    goal = Goal.find(params[:id])
    goal.toggle!(:completed)

    redirect_to current_user
  end

  private

  def goal_params
    params.require(:goal).permit(:body, :public)
  end

  def require_correct_user
    unless Goal.find(params[:id]).user_id == current_user.id
      flash[:warning] = "Stop that."
      redirect_to current_user
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = "Invalid credentials"
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @goals = @user == current_user ? @user.goals : @user.goals.where(public: true)
    @comments = @user.comments.includes(:author)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = <<-HTML
      <input
        type="hidden"
        name="authenticity_token"
        value="#{form_authenticity_token}">
    HTML

    html.html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= comment.body %><br>
Written by <%= comment.author.username %>.
<% if current_user == comment.author %>
  <%= button_to "Delete Comment", comment_url(comment), method: :delete %>
<% end %>

app/views/goals/_goal.html.erb
<%= goal.body %><br>
Completed: <%= goal.completed ? "completed" : "in progress" %><br>
Public: <%= goal.public ? "public" : "private" %><br>
Number of cheers: <%= goal.cheers.length %><br>
<% if goal.user == current_user %>
  <%= link_to "Edit Goal", edit_goal_url(goal) %><br>
  <% if !goal.completed %>
    <%= button_to "Mark Completed", toggle_goal_url(goal) %>
  <% else %>
    <%= button_to "Mark In Progress", toggle_goal_url(goal) %>
  <% end %>
  <%= button_to "Delete Goal", goal_url(goal), method: :delete %>
<% end %>
<%= link_to "Comment On Goal", goal_url(goal) %>

<% unless current_user.cheered_goals.include?(goal) %>
  <%= button_to "Cheer this goal", cheer_goal_url(goal) %>
<% end %>

<br>

<h3>Comments on the this goal:</h3>
<%= render goal.comments.includes(:author) %>

app/views/goals/edit.html.erb
<h1>Update Goal</h1>

<form action="<%= goal_url(@goal) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>

  <label for="goal-body">Goal
    <input type="text" id="goal-body" name="goal[body]" value="<%= @goal.body %>">
  </label><br>

  <label for="goal-public">Public
    <input
      type="radio"
      id="goal-public"
      name="goal[public]"
      value="true"
      <%= "checked" if @goal.public %>>
  </label><br>
  <label for="goal-private">Private
    <input
      type="radio"
      id="goal-private"
      name="goal[public]"
      value="false"
      <%= "checked" unless @goal.public %>>
  </label><br>

  <input type="submit" value="Update Goal">
</form>

app/views/goals/new.html.erb
<h1>Create Goal</h1>

<form action="<%= goals_url %>" method="POST">
  <%= auth_token %>

  <label for="goal-body">Goal
    <input type="text" id="goal-body" name="goal[body]" value="<%= @goal.body %>">
  </label><br>

  <label for="goal-public">Public
    <input type="radio" id="goal-public" name="goal[public]" value="true">
  </label><br>
  <label for="goal-private">Private
    <input type="radio" id="goal-private" name="goal[public]" value="false">
  </label><br>

  <input type="submit" value="Create Goal">
</form>

app/views/goals/show.html.erb
<%= render @goal %>

<h4>Comment on this goal</h4>
<form action="<%= comments_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="comment[commentable_type]" value="Goal">
  <input type="hidden" name="comment[commentable_id]" value="<%= @goal.id %>">
  <label for="comment-body">Add Comment
    <textarea name="comment[body]" id="comment-body"></textarea>
  </label>
  <br>
  <input type="submit" value="Add Comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% unless flash.empty? %>
  <% flash.each do |type, message| %>
    <div><%= message %></div>
  <% end %>
<% end %>



<%= yield %>


<% if current_user %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% end %>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  <%= auth_token %>

  <label for="user-username">Username
    <input type="text" id="user-username" name="user[username]" value="<%= @user.username %>">
  </label><br>

  <label for="user-password">Password
    <input type="password" id="user-password" name="user[password]">
  </label><br>

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= render @goals, user: @user %>

<h3>Comments about <%= @user.username %></h3>
<%= render @comments %>

<h4>Comment on User</h3>
<form action="<%= comments_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="comment[commentable_type]" value="User">
  <input type="hidden" name="comment[commentable_id]" value="<%= @user.id %>">
  <label for="comment-body">Add Comment
    <textarea name="comment[body]" id="comment-body"></textarea>
  </label>
  <br>
  <input type="submit" value="Add Comment">
</form>